apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: robinhood-auth-pvc
  namespace: robinhood
  labels:
    app: robinhood-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
