apiVersion: v1
kind: Service
metadata:
  name: robinhood-agent-service
  namespace: robinhood
  labels:
    app: robinhood-agent
spec:
  type: ClusterIP
  selector:
    app: robinhood-agent
  ports:
    - port: 8000
      targetPort: 8000
      name: http
